### PR TITLE
Make parent configurable

### PR DESCRIPTION
**Pull request by dansingerman**
Make parent configurable, so it will work in apps that use a model other than Team for the endpoints and webhook issuing models

### CODE REVIEW

**Comment by andrewculver** [comment]
@dansingerman Sorry, I took too long to merge some stuff from @petekeen-cf and now this PR is conflicting. Do you mind resolving the conflicts?

**Comment by dansingerman** [comment]
> @dansingerman Sorry, I took too long to merge some stuff from @petekeen-cf and now this PR is conflicting. Do you mind resolving the conflicts?

I think I have resolved them locally, but I have a failing test, that I don't think the merge introduced: in `Webhooks::Outgoing::IssuingModel` , `endpoints_listening_for_event_type?` is called as an instance method:

```
if team.endpoints_listening_for_event_type?(event_type)
```

but it's defined in `Webhooks::Outgoing::TeamSupport` as a class method, so I get this failing test:

```
Error:
WebhooksSystemTest#test_team_member_registers_for_webhooks_and_then_receives_them_on_macbook_pro_15_inch:
NoMethodError: undefined method `endpoints_listening_for_event_type?' for #<Team id: 9889, name: "Your Team", slug: nil, created_at: "2022-07-26 07:36:46.715991000 +0000", updated_at: "2022-07-26 07:36:46.715991000 +0000", being_destroyed: nil, time_zone: nil, locale: nil>
    test/factories/users.rb:17:in `block (4 levels) in <main>'
    test/system/webhooks_system_test.rb:6:in `setup'
```

I guess I can fix that here, but want to check I'm not missing something? Not sure why the CI is passing with this failing test, so that's also a concern.

**Comment by andrewculver** [comment]
@dansingerman Yes, please go ahead and fix it. I’ll update the CI config to run the local test suite before merging.

**Comment by andrewculver** [comment]
@dansingerman I had to revert the other PRs, so chances are this will merge cleanly now.

**Pull request merged**
